"""make image hash unique

Revision ID: 874209ab88a2
Revises: 0fb3cc4bfbd9
Create Date: 2026-03-07 22:06:43.597982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "874209ab88a2"
down_revision: Union[str, Sequence[str], None] = "0fb3cc4bfbd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "image", ["hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "image", type_="unique")
    # ### end Alembic commands ###
