"""embeddings and cascade delete

Revision ID: e4fe780de05f
Revises: 9d9729b2102b
Create Date: 2026-02-23 23:37:57.685800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "e4fe780de05f"
down_revision: Union[str, Sequence[str], None] = "9d9729b2102b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("image", "thumb", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "image",
        "embeddings",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_serviceq_pending"),
        table_name="serviceq",
        postgresql_where="(attempts < max_attempts)",
    )
    op.drop_constraint(op.f("serviceq_image_id_fkey"), "serviceq", type_="foreignkey")
    op.create_foreign_key(
        None, "serviceq", "image", ["image_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "serviceq", type_="foreignkey")
    op.create_foreign_key(
        op.f("serviceq_image_id_fkey"), "serviceq", "image", ["image_id"], ["id"]
    )
    op.create_index(
        op.f("idx_serviceq_pending"),
        "serviceq",
        ["status", "created_at"],
        unique=False,
        postgresql_where="(attempts < max_attempts)",
    )
    op.alter_column(
        "image",
        "embeddings",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=3),
        existing_nullable=True,
    )
    op.alter_column("image", "thumb", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
